spring:
  application:
    name: Messender
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    username: admin
    password: admin
    url: jdbc:h2:file:./demo
  h2:
    console:
      enabled: true
      path: /console
security:
  jwt:
    token:
      secret-key: DASasCAXCAS9asfd129dasvsagnjksdNISADF